# Generated by Django 5.2.1 on 2025-09-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.darkhast')),
            ],
        ),
    ]
