# Generated by Django 5.2.1 on 2025-10-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0002_alter_board_status_alter_historicalboard_status'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletPartFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.part')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.darkhast')),
            ],
        ),
    ]
