# Generated by Django 5.2.1 on 2025-10-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0005_alter_sepehrqc_status'),
        ('finance', '0002_paletpartfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.CharField(max_length=100)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anbar.board')),
            ],
        ),
    ]
