# Generated by Django 5.2.1 on 2025-11-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_usedorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkhastFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=25)),
                ('sets', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='paletfinance',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.darkhastfinance'),
        ),
        migrations.AlterField(
            model_name='paletpartfinance',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.darkhastfinance'),
        ),
    ]
