# Generated by Django 5.2.1 on 2025-11-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0009_boardoperation_operation_type'),
        ('finance', '0004_darkhastfinance_alter_paletfinance_req_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkhastfinance',
            name='project',
        ),
        migrations.AlterField(
            model_name='darkhastfinance',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.board'),
        ),
    ]
