# Generated by Django 5.2.1 on 2025-11-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_darkhastfinance_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletfinance',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('CN', 'Conditional'), ('ND', 'Not Determined'), ('NA', 'Not Aveilable')], default='ND', max_length=2),
        ),
    ]
