# Generated by Django 5.2.1 on 2025-11-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_paletfinance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletfinance',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('CN', 'Conditional'), ('ND', 'Not Determined'), ('NA', 'Not Available')], default='ND', max_length=2),
        ),
    ]
