# Generated by Django 5.2.1 on 2025-11-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0010_order_status_delete_historicalorder'),
        ('finance', '0007_alter_paletfinance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletfinance',
            name='description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paletfinance',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anbar.order'),
        ),
    ]
