# Generated by Django 5.2.1 on 2026-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_paletfinance_description_paletfinance_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paletfinance",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
