# Generated by Django 5.2.1 on 2025-09-23 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anbar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EPT', 'empty'), ('PRT', 'has part'), ('SEP', 'separated')], default='EPT', max_length=6)),
                ('type', models.CharField(choices=[('BILLET', 'billet'), ('SHEET', 'sheet'), ('SCRAP', 'scrap')], max_length=6)),
                ('length', models.SmallIntegerField(blank=True, null=True)),
                ('width', models.SmallIntegerField(blank=True, null=True)),
                ('hight', models.SmallIntegerField(blank=True, null=True)),
                ('alloy', models.CharField(max_length=25)),
                ('order', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=40, unique=True)),
                ('condition', models.CharField(choices=[('REJ', 'rejected'), ('DMG', 'damaged'), ('INC', 'intact')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mech.material')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DUM', 'dummy'), ('CON', 'connected'), ('SEP', 'separated'), ('FIN', 'finished')], default='CON', max_length=3)),
                ('part_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=3)),
                ('version', models.CharField(max_length=2)),
                ('serial', models.CharField(max_length=5)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mech.material')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.project')),
            ],
        ),
        migrations.CreateModel(
            name='PartOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mech.part')),
            ],
        ),
    ]
