# Generated by Django 5.2.1 on 2025-10-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_remove_product_project_boardpack'),
        ('mech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mech.part')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.product')),
            ],
        ),
    ]
