# Generated by Django 5.2.1 on 2025-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mech', '0002_partpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('DUM', 'dummy'), ('CON', 'connected'), ('SEP', 'separated'), ('FIN', 'finished'), ('ASM', 'assembled')], default='CON', max_length=3),
        ),
    ]
