# Generated by Django 5.2.1 on 2025-10-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mech', '0003_alter_part_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('DUM', 'dummy'), ('CON', 'connected'), ('SEP', 'separated'), ('ASM', 'assembly'), ('FIN', 'finished')], default='CON', max_length=3),
        ),
    ]
