# Generated by Django 5.2.1 on 2025-11-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mech', '0004_alter_part_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkhastMech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FIN', 'Finished'), ('PND', 'Pending')], default='PND', max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('DUM', 'Dummy'), ('CON', 'Connected'), ('SEP', 'Separated'), ('ASM', 'Assembly'), ('FIN', 'Finished')], default='CON', max_length=3),
        ),
        migrations.CreateModel(
            name='DarkhastMechPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mech.part')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mech.darkhastmech')),
            ],
        ),
    ]
