# Generated by Django 5.2.1 on 2025-10-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QCBoardOperation',
        ),
    ]
