from django.urls import path
from .views import *

urlpatterns = [
    path('parts/', part_list , name='part_list'),
    path('add_parts/', part_add , name='part_add'),
    path('download-part-template/', download_part_template, name='download_part_template'),
    path('download-bom-template/', download_bom_template, name='download_bom_template'),
    path('export_excel/<int:pk>', export_excel_req, name='export_excel'),
    path('history/', part_history, name ='part_history'),
    path('partbom/', part_bom , name='part_bom'),
    path('export_excel_logs/', export_excel_logs, name='export_excel_logs'),
    path('board_all/', board_list, name='board_list'),
    path('board_all/<str:projectname>/<str:title>', board_title, name='board_title'),
    path('board_all/<str:projectname>/<str:title>/<str:version>', board_title_version, name='board_title_version'),
    path('board_all/<str:projectname>/<str:title>/<str:version>/<str:pk>/', bom_details, name ='bom_details'),
    path('boards/<str:projectname>/', board_details, name='board_details'),
    path('boards/<str:projectname>/<str:title>/', board_version, name='board_version'),
    path('boards/<str:projectname>/<str:title>/<str:version>', board_version_bom, name='board_version_bom'),
    path('board_add/', board_add, name='board_add'),
    path('bom_preview/<str:project>/<str:title>/<str:version>', bom_preview, name ='bom_preview'),
    path('projects/', project_list, name ='project_list'),
    path('project/', project_add, name ='project_add'),
    path('darkhast/', darkhast, name ='darkhast'),
    path('darkhast_completion/', darkhast_completion, name ='darkhast_completion'),
    path('darkhast_completion/<str:projectname>/<str:title>/', darkhast_completion_boards, name ='darkhast_completion_boards'),
    path('darkhast_acc/', darkhast_acc, name ='darkhast_acc'),
    path('darkhast_part/', darkhast_part, name ='darkhast_part'),
    path('panel_anbardar/', panel_anbardar, name ='panel_anbardar'),
    path('panel_anbardar/<int:pk>', panel_anbardar_details, name ='panel_anbardar_details'),
    path('panel_anbardar/maf/<int:pk>', panel_anbardar_maf_details, name ='panel_anbardar_maf_details'),
    path('panel_anbardar/res/<int:pk>', panel_anbardar_res_details, name ='panel_anbardar_res_details'),
    path('panel_anbardar/acc/<int:pk>', panel_anbardar_acc, name ='panel_anbardar_acc'),
    path('panel_assemble/', panel_assemble, name ='panel_assemble'),
    path('panel_assemble/<int:pk>', panel_assemble_board, name ='panel_assemble_board'),
    path('panel_assemble/<int:pk>/<int:pk2>', panel_assemble_details, name ='panel_assemble_details'),
    path('panel_assemble/acc/<int:pk>/<int:pk2>', panel_assemble_acc, name ='panel_assemble_acc'),
    path('flow/', flow, name ='flow'),
    path('change_assembler/<int:pk>/', change_assembler, name ='change_assembler'),
    path('send-qc/', send_to_qc, name ='send_to_qc'),
]
