# Generated by Django 5.2.1 on 2025-09-23 09:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QC', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaletAnbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('part_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('status', models.CharField(choices=[('NR', 'not received'), ('OR', 'ordered'), ('RC', 'received'), ('RB', 'raw board'), ('PD', 'pending'), ('PA', 'partial assemble'), ('CA', 'complete assemble'), ('QC', 'sent to QC'), ('SP', 'Sepehr QC')], default='NR', max_length=2)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('serial', models.CharField(blank=True, max_length=5, null=True)),
                ('qc_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QC.qcrequest')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.board')),
                ('operator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('designators', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PND', 'pending'), ('TV', 'tahvil'), ('AS', 'asselmbled'), ('EPT', 'empty')], default='EPT', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.board')),
            ],
        ),
        migrations.CreateModel(
            name='Darkhast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('PND', 'pending')], default='PND', max_length=3)),
                ('description', models.TextField()),
                ('req_type', models.CharField(blank=True, choices=[('FIN', 'finance'), ('ASS', 'assemble'), ('COM', 'completion'), ('MAF', 'mafghood'), ('QC', 'QC'), ('MCH', 'mechanic')], max_length=3, null=True)),
                ('for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('order_date', models.DateField(blank=True, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPart',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('part_number', models.CharField(max_length=50)),
                ('package', models.CharField(blank=True, max_length=15, null=True)),
                ('part_value', models.CharField(blank=True, max_length=10, null=True)),
                ('failure', models.CharField(choices=[('REJECT', 'rejected'), ('ACCEPT', 'accepted'), ('COND1', 'conditional type_1'), ('COND2', 'conditional type_2'), ('COND3', 'conditional type_3')], default='ACCEPT', max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('reserve', models.IntegerField(default=0)),
                ('price', models.SmallIntegerField(default=0)),
                ('freeze', models.SmallIntegerField(default=0)),
                ('changed_request', models.CharField(default='System', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anbar.order')),
            ],
            options={
                'verbose_name': 'historical part',
                'verbose_name_plural': 'historical parts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=50)),
                ('package', models.CharField(blank=True, max_length=15, null=True)),
                ('part_value', models.CharField(blank=True, max_length=10, null=True)),
                ('failure', models.CharField(choices=[('REJECT', 'rejected'), ('ACCEPT', 'accepted'), ('COND1', 'conditional type_1'), ('COND2', 'conditional type_2'), ('COND3', 'conditional type_3')], default='ACCEPT', max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('reserve', models.IntegerField(default=0)),
                ('price', models.SmallIntegerField(default=0)),
                ('freeze', models.SmallIntegerField(default=0)),
                ('changed_request', models.CharField(default='System', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.order')),
            ],
        ),
        migrations.CreateModel(
            name='Palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.bom')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.darkhast')),
                ('palet_anbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.paletanbar')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.part')),
            ],
        ),
        migrations.CreateModel(
            name='Mafghood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.darkhast')),
                ('maf_part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.part')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBoard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('NR', 'not received'), ('OR', 'ordered'), ('RC', 'received'), ('RB', 'raw board'), ('PD', 'pending'), ('PA', 'partial assemble'), ('CA', 'complete assemble'), ('QC', 'sent to QC'), ('SP', 'Sepehr QC')], default='NR', max_length=2)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('serial', models.CharField(blank=True, max_length=5, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qc_req', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QC.qcrequest')),
                ('project_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anbar.project')),
            ],
            options={
                'verbose_name': 'historical board',
                'verbose_name_plural': 'historical boards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SepehrQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RP', 'repairing'), ('SN', 'sent'), ('RC', 'received')], max_length=2)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.board')),
            ],
        ),
        migrations.CreateModel(
            name='ReStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('res_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anbar.part')),
                ('sep_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.sepehrqc')),
            ],
        ),
    ]
