# Generated by Django 5.2.1 on 2025-09-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('NR', 'Not Received'), ('OR', 'Ordered'), ('RC', 'Received'), ('RB', 'Raw Board'), ('PD', 'Pending'), ('PA', 'Partial Assemble'), ('CA', 'Complete Assemble'), ('QC', 'Sent to QC'), ('SP', 'Sepehr QC'), ('AS', 'Assembly'), ('FN', 'Finished')], default='NR', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='status',
            field=models.CharField(choices=[('NR', 'Not Received'), ('OR', 'Ordered'), ('RC', 'Received'), ('RB', 'Raw Board'), ('PD', 'Pending'), ('PA', 'Partial Assemble'), ('CA', 'Complete Assemble'), ('QC', 'Sent to QC'), ('SP', 'Sepehr QC'), ('AS', 'Assembly'), ('FN', 'Finished')], default='NR', max_length=2),
        ),
    ]
