# Generated by Django 5.2.1 on 2025-10-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0002_alter_board_status_alter_historicalboard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mafghood',
            name='maf_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.part'),
        ),
    ]
