# Generated by Django 5.2.1 on 2025-10-11 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0003_alter_mafghood_maf_part'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sepehrqc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sepehrqc',
            name='status',
            field=models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('PND', 'pending')], max_length=3),
        ),
    ]
