# Generated by Django 5.2.1 on 2025-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0004_sepehrqc_user_alter_sepehrqc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepehrqc',
            name='status',
            field=models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('PND', 'pending')], default='PND', max_length=3),
        ),
    ]
