# Generated by Django 5.2.1 on 2025-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0005_alter_sepehrqc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpart',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
