# Generated by Django 5.2.1 on 2025-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0006_alter_historicalpart_count_alter_part_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepehrqc',
            name='status',
            field=models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('NOR', 'not ordered'), ('PND', 'pending')], default='NOR', max_length=3),
        ),
    ]
