# Generated by Django 5.2.1 on 2025-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0007_alter_sepehrqc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkhast',
            name='req_type',
            field=models.CharField(blank=True, choices=[('FIN', 'Finance'), ('ASS', 'Assemble'), ('COM', 'Completion'), ('MAF', 'Mafghood'), ('QC', 'QC'), ('MCH', 'Mechanic')], max_length=3, null=True),
        ),
    ]
