# Generated by Django 5.2.1 on 2025-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0008_alter_darkhast_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardoperation',
            name='operation_type',
            field=models.CharField(choices=[('QC', 'QC'), ('AS', 'Assemble')], default='AS', max_length=2),
            preserve_default=False,
        ),
    ]
