# Generated by Django 5.2.1 on 2025-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0009_boardoperation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRE', 'PreOrder'), ('ORD', 'Ordered'), ('RCV', 'Received')], default='PRE', max_length=3),
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
