# Generated by Django 5.2.1 on 2026-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anbar", "0010_order_status_delete_historicalorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpart",
            name="price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="part",
            name="price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
