# Generated by Django 5.2.1 on 2025-09-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anbar', '0002_alter_board_status_alter_historicalboard_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnumber', models.IntegerField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MEC', 'Mechanic'), ('ELC', 'Electronic'), ('SFT', 'Software')], max_length=3)),
                ('partnumber', models.CharField(max_length=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.project')),
            ],
        ),
    ]
