# Generated by Django 5.2.1 on 2025-10-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0002_alter_board_status_alter_historicalboard_status'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Project',
        ),
        migrations.CreateModel(
            name='BoardPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anbar.board')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.product')),
            ],
        ),
    ]
