# Generated by Django 5.2.1 on 2025-10-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0002_alter_board_status_alter_historicalboard_status'),
        ('assembly', '0002_remove_product_project_boardpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anbar.project'),
            preserve_default=False,
        ),
    ]
