# Generated by Django 5.2.1 on 2025-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_product_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productnumber',
            field=models.CharField(max_length=25),
        ),
    ]
